config/routes.rb
Proto2::Application.routes.draw do
  resources :messages, :only => [:new, :create]

  root :to => "home#index"

end

app/models/message.rb
class Message
  include ActiveModel::Validations

  validates_presence_of :email, :sender_name, :subject, :message_type, :content
  # to deal with form, you must have an id attribute
  attr_accessor :id, :email, :sender_name, :subject, :message_type, :content

  def initialize(attributes = {})
    attributes.each do |key, value|
      self.send("#{key}=", value)
    end
    @attributes = attributes
  end

  def read_attribute_for_validation(key)
    @attributes[key]
  end

  def to_key
  end

  def save
    if self.valid?
      Notifier.message_notification(self).deliver
      return true
    end
    return false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    # id is required to deal with form
    @message = Message.new(:id => 1)
  end

  def create
    @message = Message.new(params[:message])
    if @message.save
      redirect_to('/', :notice => "Message was successfully sent.")
    else
      flash[:alert] = "You must fill all fields."
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_active?(page_name)
    "active" if params[:action] == page_name
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/home/index.html.erb
<!-- Content -->
<fieldset>
<legend>&nbsp;NEWS&nbsp;</legend>
<br />
Another prototype...
</fieldset>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US" xml:lang="en">
<head>
  <title>Team Awesome CS4283 Prototype</title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<div id="content"><div id="container"><div id="content2">

  <!-- Navigation bar -->
  <ul id="vertical-navigation">
    <li class=""> <a href="#">About</a>
      <ul>
        <li class=""> <a href="#">Roadmap</a> </li>
        <li class=""> <a href="#">Contact Us</a> </li>
      </ul>
    </li>
    <li class=""> <a href="#">Manage</a>
      <ul>
        <li class=""> <a href="#">Add</a> </li>
        <li class=""> <a href="#">Remove</a> </li>
      </ul>
    </li>
    <li class=""> <%= link_to 'Send', new_message_path, :class => is_active?("new") %> </li>
    <li class=""> <%= link_to 'Home', '/', :class => is_active?("index") %> </li>
  </ul><br /><br /><br /><br /><br />

  <%= yield %>

  <!-- Footer -->
  <ul id="footer">
    <li class=""> <a href="http://jigsaw.w3.org/css-validator/check/referer">Valid CSS Level 3</a> </li>
    <li class=""> <a href="http://validator.w3.org/check?uri=referer">Valid XHTML 1.0 Strict</a> </li>
    <li class=""> <a href="http://www.rubyonrails.org/">Ruby on Rails</a> </li>
  </ul>

</div></div></div>
</body>
</html>

app/views/messages/_form.html.erb
<% form_for @message, :url => { :action => "create" }, :html => { :method => :post } do |f| %>
<div id="formleft" style="width: 100%">
  <%= f.label "Name" %>
  <%= f.text_field :sender_name, :size => "13" %><br />
  <%= f.label "Email" %>
  <%= f.text_field :email, :size => "13" %><br />
  <%= f.label "Type" %>
  <%= f.select :message_type, options_for_select(["Announcement", "Urgent"]) %><br /><br />
  <%= f.label "Subject" %>
  <%= f.text_field :subject, :size => "35" %><br />
  <%= f.label "Message" %>
  <%= f.text_area :content, :rows => "8", :cols => "40" %><br /><br />
</div>
<div id="formright" style="padding-right: 225px">
  <%= f.label " " %>
  <%= f.submit "Submit" %>
  <%= submit_tag("Clear", { :name => "reset", :id => "reset", :type => "reset" }) %>
</div>
<div class="clear"></div>
<% end %>

app/views/messages/new.html.erb
<!-- Content -->
<fieldset>
  <legend>&nbsp;SEND MESSAGE&nbsp;</legend>
  <br />
  <%= render 'form' %>
</fieldset>

app/views/notifier/message_notification.html.erb
message from
<b><%= @sender.sender_name %></b>
&lt;<i><%= @sender.email %></i>&gt;...
<br /><br />
<%= @sender.content %>